### ISSUE TITLE
Error: 13 Library Not Valid

### ISSUE THREAD

**Issue by Ewoannon** [codewitch-honey-crisis/gfx#16]
Attempting to install library through Arduino IDE 2.0 library manager returns the following error message:
`Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid` 
Any solutions would be much appreciated. 
Mòran taing.

**Comment by codewitch-honey-crisis** [comment]
As far as I know Arduino cannot handle htcw_gfx because it requires C++14 or better to compile. That's why it's not an Arduino library. Use platformIO.
