### ISSUE TITLE
If this is the website, where is the "real" code I *can* clone? Don't you think you can document this kind of thing a little better?

### ISSUE THREAD

**Issue by WyoMurf** [codewitch-honey-crisis/gfx#32]
The fact that I have to file two issues to find out what the deal is, is not a good sign!

**Comment by codewitch-honey-crisis** [comment]
First of all, most people who use "git" know that they cannot just git clone an arbitrary website. This is a git user education issue, not a gfx issue.

Second, at that website that you tried to clone, there is a prominent link to the github repo, right on the landing page.

Finally, in over a year and half, you're the only one that's ever hit any of my projects by trying to clone my website and then opening an issue about it.

So no, I'm not going to personalize my documentation for you.
