### ISSUE TITLE
Logic flaw in gfx/include/gfx_drawing.hpp::text_impl (3183 ff)

### ISSUE THREAD

**Issue by fschuetz** [codewitch-honey-crisis/gfx#8]
gfx/include/gfx_drawing.hpp::text_impl (3183 ff) contains a logic flaw when rendering text. On line 3222, 3214 and 3266 the following check is done:

`if(chr.y2>dest_rect.bottom()) {
           return gfx_result::success;
}`

This check I assume should stop drawing when it would render text outside the target. However, there are two problems:

1) the check (verified with the code block around 3266) is only done after drawing the first character. So the first character is always drawn.
2) the check uses y2, which lead to partially visible text not rendered as the top might be in the visible range, but the bottom is not (assume target of height 4 pixels but font height 8 pixels. The assumption would be the top half of the text is rendered. Can easily be fixed by replacing y2 with y1.

The behaviour can be verified by for example on a 128x160 (landscape) display drawing text in a are that is smaller than the font height. For example:

`draw::text(destination, 
                        remaining_area,
                        item_ptr->name,
                        font,
                        col); `

with destination the lcd, remaining_area (0,122)(159,127).

**Comment by codewitch-honey-crisis** [comment]
Thank you. I'll fix as soon as I can. I am buried with work at the moment, but I really appreciate you running this down for me.

**Comment by fschuetz** [comment]
Yes, I see the idea. However, the current implementation will draw one character (that might partially fit the screen, eg. the upper part of A), but not the rest of the string (eg. BCDE if the string were "ABCDE") even though their upper parts would also be visible.

**Comment by codewitch-honey-crisis** [comment]
fixed in 1.3.5
